"""
Static data inventory for CCMS.

Describes, per data category: what is collected, why, where stored, who can
access it, and the default retention expectation. Used by the admin
`GET /api/privacy/data-inventory` endpoint and by CCPA/HIPAA/ISO readiness docs.

This is NOT a legal document. It is a structured internal reference meant to
align Engineering with whatever the organisation's published Privacy Notice
ultimately says. Retention durations here are application defaults; the
governing value in production is set by a configured retention policy
(see `PRIVACY_AND_RETENTION.md`).
"""

DATA_INVENTORY: list[dict] = [
    {
        "id": "identity_account",
        "name": "Identity & account data",
        "collected": [
            "email (unique login)",
            "name",
            "phone",
            "role",
            "password hash (bcrypt)",
            "MFA secret + backup codes (when enrolled)",
            "session epoch + login metadata",
        ],
        "purpose": "Authenticate users, enforce RBAC, drive MFA, protect against brute force, meet HIPAA access-control requirements.",
        "legal_basis_hints": ["contract", "legitimate_interest", "legal_obligation"],
        "storage": "MongoDB `users` collection (relational schema in services/identity/models.py)",
        "encrypted_at_rest": "password hashed (bcrypt); MFA secret stored as plaintext field (should be KMS-wrapped in production — P0 backlog)",
        "access_roles": ["self", "admin"],
        "retention_default": "Active + 3 years after account disable (configurable via RETENTION_IDENTITY_YEARS)",
        "ccpa_category": "Identifiers / professional information",
        "phi": False,
    },
    {
        "id": "patient_profile",
        "name": "Patient profile (PHI)",
        "collected": [
            "first_name",
            "last_name",
            "date_of_birth",
            "gender",
            "phone",
            "email",
            "address (encrypted)",
            "emergency_contact (encrypted)",
            "notes (encrypted)",
            "user_id link",
        ],
        "purpose": "Clinical care, appointment scheduling, and legally-required recordkeeping.",
        "legal_basis_hints": ["treatment", "legal_obligation", "vital_interest"],
        "storage": "MongoDB `patients` collection. Free-text fields encrypted with AES-256-GCM (`core/crypto.py`).",
        "encrypted_at_rest": "address, emergency_contact, notes (authenticated-encryption, `enc:v1:` prefix)",
        "access_roles": ["admin", "doctor", "staff", "patient (self)"],
        "retention_default": "7 years after soft-delete (configurable via RETENTION_YEARS; jurisdiction-dependent — see PRIVACY_AND_RETENTION.md §4)",
        "ccpa_category": "Medical / health information",
        "phi": True,
    },
    {
        "id": "medical_records",
        "name": "Medical records (PHI)",
        "collected": [
            "patient_id",
            "record_type",
            "description (encrypted)",
            "diagnosis (encrypted)",
            "treatment (encrypted)",
            "recorded_by_id",
            "recorded_at",
        ],
        "purpose": "Clinical treatment continuity and legal medical recordkeeping.",
        "legal_basis_hints": ["treatment", "legal_obligation"],
        "storage": "MongoDB `medical_records` collection. All clinical free-text encrypted at rest.",
        "encrypted_at_rest": "description, diagnosis, treatment",
        "access_roles": ["admin", "doctor (treating or break-glass)", "patient (self via export)"],
        "retention_default": "Follows patient retention. Medical-record retention is jurisdiction-dependent (e.g. US state boards: 6–10 years for adults, until age of majority + N for minors). Configure per deployment.",
        "ccpa_category": "Medical / health information",
        "phi": True,
    },
    {
        "id": "appointments",
        "name": "Appointment data",
        "collected": [
            "patient_id",
            "provider_id",
            "start_time",
            "end_time",
            "status",
            "reason",
            "notes (encrypted)",
        ],
        "purpose": "Scheduling, availability, capacity planning, billing provenance.",
        "legal_basis_hints": ["contract", "treatment"],
        "storage": "MongoDB `appointments` collection.",
        "encrypted_at_rest": "notes",
        "access_roles": ["admin", "doctor (own or break-glass)", "staff", "patient (own)"],
        "retention_default": "Linked to patient retention window.",
        "ccpa_category": "Medical / commercial",
        "phi": True,
    },
    {
        "id": "notifications",
        "name": "Notification / contact history",
        "collected": [
            "type (email|sms)",
            "recipient_id",
            "to_address",
            "body (masked unless unmask=true)",
            "status",
            "sent_at",
            "metadata (appointment_id, template, etc.)",
        ],
        "purpose": "Transactional appointment reminders, confirmations, and communication audit trail.",
        "legal_basis_hints": ["contract", "legitimate_interest"],
        "storage": "MongoDB `notifications` collection.",
        "encrypted_at_rest": "not currently — mock integration. Real delivery (Twilio/Resend) should wrap body in encryption at rest.",
        "access_roles": ["admin", "staff"],
        "retention_default": "2 years for transactional messages; marketing messages follow consent records.",
        "ccpa_category": "Identifiers / commercial information",
        "phi": True,
    },
    {
        "id": "audit_logs",
        "name": "Audit & security records",
        "collected": [
            "action",
            "actor (id, email, role)",
            "entity (type, id)",
            "outcome",
            "reason",
            "metadata (ids, enums, counts — NEVER PHI values)",
            "phi_accessed flag",
            "ip",
            "user_agent",
            "created_at",
        ],
        "purpose": "HIPAA §164.312(b) audit controls, SOC 2 CC7 monitoring, incident response.",
        "legal_basis_hints": ["legal_obligation"],
        "storage": "MongoDB `audit_logs` collection.",
        "encrypted_at_rest": "no (audit rows themselves contain no PHI values; integrity is the priority)",
        "access_roles": ["admin"],
        "retention_default": "7 years (configurable via RETENTION_AUDIT_YEARS).",
        "ccpa_category": "Internet / system activity; inference data",
        "phi": False,
    },
    {
        "id": "consent_records",
        "name": "Consent records",
        "collected": [
            "user_id",
            "policy_type",
            "policy_version",
            "action (accepted|withdrawn)",
            "accepted_at",
            "ip",
            "user_agent",
        ],
        "purpose": "Prove when and to which version a user accepted the Privacy Notice / Terms / marketing consent.",
        "legal_basis_hints": ["legal_obligation"],
        "storage": "MongoDB `consent_records` collection.",
        "encrypted_at_rest": "no",
        "access_roles": ["self", "admin"],
        "retention_default": "Lifetime of account + audit retention window.",
        "ccpa_category": "Identifiers / internet activity",
        "phi": False,
    },
    {
        "id": "privacy_requests",
        "name": "Privacy requests (DSARs)",
        "collected": [
            "request_type",
            "subject_user_id",
            "submitted_by_id",
            "status",
            "notes",
            "response_notes",
            "fulfillment (rows exported, entity ids soft-deleted)",
            "timestamps",
        ],
        "purpose": "Record, track and demonstrate fulfilment of data-subject access / deletion / correction / opt-out requests.",
        "legal_basis_hints": ["legal_obligation"],
        "storage": "MongoDB `privacy_requests` collection.",
        "encrypted_at_rest": "no — notes fields must NOT contain PHI; enforced by convention + policy.",
        "access_roles": ["admin", "submitter"],
        "retention_default": "Follow audit retention.",
        "ccpa_category": "Inference / system activity",
        "phi": False,
    },
]
