"""
CCMS authorization — source-of-truth permission catalogue + baseline grants.

Design principles (encoded here):
  * default-deny: a role only gets what is in its grant list
  * least privilege: patient portal = self only; IA = minimal read
  * separation of duties: view != export, create != approve
  * explicit policy flags (MFA / APR / BG) per grant, not baked into name
  * stable machine name: `resource.action`; scope + flags stored separately

Legend (from the Permission Matrix PDF):
  N  = not granted
  L  = limited (scope=assigned_location OR phi_limited)
  F  = full within role's natural scope (all_org or all_location_patients)
  A  = approval required (approval flag added)
  E  = export allowed  (permission is an explicit `.export` action)
  S  = sign allowed    (permission is an explicit `.sign` action)
  BG = break-glass allowed
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

RESOURCES: list[str] = [
    "patient", "patient_chart", "soap_note", "treatment_plan",
    "appointment", "waitlist", "intake_form",
    "insurance", "eligibility",
    "billing", "charge", "payment", "adjustment",
    "claim", "remit", "coding",
    "document",
    "message", "broadcast", "secure_message",
    "consent", "privacy_request", "retention_policy", "release_of_information",
    "audit_log", "phi_access_report", "access_review", "security_event",
    "user", "service_account", "role", "permission",
    "org_settings", "clinic_settings", "template",
    "reporting", "dashboard",
    "integration", "api_key", "webhook",
    "self", "session",
    "break_glass",
    "settings",  # alias for org_settings in router guards
]

ACTIONS: list[str] = [
    "read", "create", "update", "delete",
    "assign", "approve", "export", "sign", "submit", "manage",
    "disable", "enable", "invite", "unlock", "reset_mfa",
    "lock", "revoke", "capture", "verify_identity",
    "fulfill_export", "fulfill_delete_anonymize",
    "deliver", "rotate",
    "override_rules", "merge_duplicate", "void", "writeoff", "refund",
    "archive", "hard_delete", "purge",
    "collect", "correct_resubmit", "activate",
    "update_metadata", "check",
    "change", "revoke_self", "revoke_other", "read_self",
]

SCOPES: list[str] = [
    "self",
    "assigned_patients",
    "assigned_location",
    "all_location_patients",
    "all_org",
    "no_phi",
    "phi_limited",
    "phi_full",
]

SENSITIVITY_LEVELS: list[str] = ["none", "low", "medium", "high", "critical"]

# ---------------------------------------------------------------------------
# Baseline roles
# ---------------------------------------------------------------------------

BASELINE_ROLES: list[dict] = [
    {"key": "super_admin", "abbr": "SA", "name": "Super Admin",
     "description": "Platform / infra / emergency admin. No routine PHI; BG only.",
     "is_system": True, "privileged": True, "legacy_role": "admin"},
    {"key": "org_owner", "abbr": "OO", "name": "Org Owner",
     "description": "Organisation owner / billable account holder.",
     "is_system": True, "privileged": True, "legacy_role": None},
    {"key": "compliance_officer", "abbr": "CO", "name": "Compliance Officer",
     "description": "HIPAA / SOC2 / CCPA compliance and audit oversight.",
     "is_system": True, "privileged": True, "legacy_role": None},
    {"key": "clinic_manager", "abbr": "CM", "name": "Clinic Manager",
     "description": "Manages a clinic location's operations.",
     "is_system": True, "privileged": False, "legacy_role": None},
    {"key": "front_desk", "abbr": "FD", "name": "Front Desk",
     "description": "Scheduling, check-in, payments, statements.",
     "is_system": True, "privileged": False, "legacy_role": None},
    {"key": "provider", "abbr": "PR", "name": "Provider / Chiropractor",
     "description": "Licensed provider; signs notes and plans.",
     "is_system": True, "privileged": False, "legacy_role": "doctor"},
    {"key": "clinical_staff", "abbr": "CS", "name": "Medical Assistant / Clinical Staff",
     "description": "Draft clinical content; cannot sign final.",
     "is_system": True, "privileged": False, "legacy_role": "staff"},
    {"key": "billing_specialist", "abbr": "BS", "name": "Billing Specialist",
     "description": "Claims, remits, ledger.",
     "is_system": True, "privileged": False, "legacy_role": None},
    {"key": "auditor", "abbr": "AU", "name": "Read-Only Auditor",
     "description": "External/internal auditor — read-only evidence access.",
     "is_system": True, "privileged": True, "legacy_role": None},
    {"key": "patient_portal", "abbr": "PP", "name": "Patient Portal User",
     "description": "Self-service. Self-scope only.",
     "is_system": True, "privileged": False, "legacy_role": "patient"},
    {"key": "integration_account", "abbr": "IA", "name": "Integration Service Account",
     "description": "Service account for API / webhook integrations. Non-human.",
     "is_system": True, "privileged": False, "legacy_role": None,
     "service_account": True},
]

ROLE_KEY_BY_ABBR = {r["abbr"]: r["key"] for r in BASELINE_ROLES}
LEGACY_ROLE_TO_KEY = {r["legacy_role"]: r["key"] for r in BASELINE_ROLES if r.get("legacy_role")}

# ---------------------------------------------------------------------------
# Permission catalogue
#
# Shape: (resource, action, sensitivity, default_flags, human_label)
# default_flags can include any of: requires_mfa, requires_approval,
# break_glass_allowed, export, destructive, phi, clinical, financial
# ---------------------------------------------------------------------------

PERMISSIONS: list[dict] = [
    # 1) Patient demographics
    {"resource": "patient", "action": "read", "sensitivity": "medium", "phi": True},
    {"resource": "patient", "action": "create", "sensitivity": "low"},
    {"resource": "patient", "action": "update", "sensitivity": "medium", "phi": True},
    {"resource": "patient", "action": "delete", "sensitivity": "critical", "destructive": True},
    {"resource": "patient", "action": "merge_duplicate", "sensitivity": "high"},
    {"resource": "patient", "action": "export", "sensitivity": "high", "export": True, "phi": True},
    # 2) Clinical chart / PHI
    {"resource": "patient_chart", "action": "read", "sensitivity": "high", "phi": True, "clinical": True},
    {"resource": "patient_chart", "action": "create", "sensitivity": "high", "phi": True, "clinical": True},
    {"resource": "patient_chart", "action": "update", "sensitivity": "high", "phi": True, "clinical": True},
    {"resource": "patient_chart", "action": "delete", "sensitivity": "critical", "destructive": True},
    {"resource": "patient_chart", "action": "manage", "sensitivity": "high", "phi": True, "clinical": True},
    # 3) SOAP / treatment
    {"resource": "soap_note", "action": "read", "sensitivity": "high", "phi": True, "clinical": True},
    {"resource": "soap_note", "action": "create", "sensitivity": "high", "phi": True, "clinical": True},
    {"resource": "soap_note", "action": "update", "sensitivity": "high", "phi": True, "clinical": True},
    {"resource": "soap_note", "action": "sign", "sensitivity": "high", "clinical": True},
    {"resource": "treatment_plan", "action": "read", "sensitivity": "high", "phi": True, "clinical": True},
    {"resource": "treatment_plan", "action": "create", "sensitivity": "high", "phi": True, "clinical": True},
    {"resource": "treatment_plan", "action": "update", "sensitivity": "high", "phi": True, "clinical": True},
    {"resource": "treatment_plan", "action": "approve", "sensitivity": "high"},
    # 4) Appointments
    {"resource": "appointment", "action": "read", "sensitivity": "medium"},
    {"resource": "appointment", "action": "create", "sensitivity": "medium"},
    {"resource": "appointment", "action": "update", "sensitivity": "medium"},
    {"resource": "appointment", "action": "delete", "sensitivity": "medium"},
    {"resource": "appointment", "action": "override_rules", "sensitivity": "high"},
    {"resource": "waitlist", "action": "manage", "sensitivity": "low"},
    # 5) Intake forms
    {"resource": "intake_form", "action": "read", "sensitivity": "medium", "phi": True},
    {"resource": "intake_form", "action": "create", "sensitivity": "medium"},
    {"resource": "intake_form", "action": "update", "sensitivity": "medium"},
    {"resource": "intake_form", "action": "lock", "sensitivity": "medium"},
    # 6) Insurance / eligibility
    {"resource": "insurance", "action": "read", "sensitivity": "medium"},
    {"resource": "insurance", "action": "create", "sensitivity": "medium"},
    {"resource": "insurance", "action": "update", "sensitivity": "medium"},
    {"resource": "insurance", "action": "export", "sensitivity": "high", "export": True},
    {"resource": "eligibility", "action": "check", "sensitivity": "low"},
    # 7) Billing
    {"resource": "billing", "action": "read", "sensitivity": "medium", "financial": True},
    {"resource": "billing", "action": "export", "sensitivity": "high", "export": True, "financial": True},
    {"resource": "charge", "action": "create", "sensitivity": "medium", "financial": True},
    {"resource": "payment", "action": "collect", "sensitivity": "medium", "financial": True},
    {"resource": "payment", "action": "refund", "sensitivity": "critical", "financial": True},
    {"resource": "adjustment", "action": "writeoff", "sensitivity": "critical", "financial": True},
    {"resource": "billing", "action": "void", "sensitivity": "critical", "financial": True, "destructive": True},
    # 8) Claims
    {"resource": "claim", "action": "read", "sensitivity": "medium", "financial": True},
    {"resource": "claim", "action": "create", "sensitivity": "medium", "financial": True},
    {"resource": "claim", "action": "submit", "sensitivity": "medium", "financial": True},
    {"resource": "claim", "action": "correct_resubmit", "sensitivity": "medium", "financial": True},
    {"resource": "remit", "action": "read", "sensitivity": "medium", "financial": True},
    {"resource": "coding", "action": "update", "sensitivity": "medium"},
    # 9) Documents
    {"resource": "document", "action": "read", "sensitivity": "medium", "phi": True},
    {"resource": "document", "action": "create", "sensitivity": "medium"},
    {"resource": "document", "action": "update_metadata", "sensitivity": "low"},
    {"resource": "document", "action": "delete", "sensitivity": "high", "destructive": True},
    {"resource": "document", "action": "sign", "sensitivity": "medium"},
    {"resource": "document", "action": "export", "sensitivity": "high", "export": True, "phi": True},
    {"resource": "document", "action": "purge", "sensitivity": "critical", "destructive": True},
    # 10) Messaging
    {"resource": "message", "action": "read", "sensitivity": "medium", "phi": True},
    {"resource": "message", "action": "create", "sensitivity": "medium"},
    {"resource": "broadcast", "action": "create", "sensitivity": "high"},
    {"resource": "secure_message", "action": "export", "sensitivity": "high", "export": True, "phi": True},
    # 11) Consents / privacy
    {"resource": "consent", "action": "read", "sensitivity": "low"},
    {"resource": "consent", "action": "capture", "sensitivity": "low"},
    {"resource": "consent", "action": "revoke", "sensitivity": "medium"},
    {"resource": "release_of_information", "action": "read", "sensitivity": "medium"},
    {"resource": "release_of_information", "action": "create", "sensitivity": "medium"},
    {"resource": "release_of_information", "action": "approve", "sensitivity": "high"},
    # 12) Audit / security evidence
    {"resource": "audit_log", "action": "read", "sensitivity": "high"},
    {"resource": "audit_log", "action": "export", "sensitivity": "high", "export": True},
    {"resource": "audit_log", "action": "delete", "sensitivity": "critical", "destructive": True},
    {"resource": "phi_access_report", "action": "read", "sensitivity": "high"},
    {"resource": "access_review", "action": "manage", "sensitivity": "high"},
    {"resource": "security_event", "action": "read", "sensitivity": "high"},
    # 13) Users
    {"resource": "user", "action": "read", "sensitivity": "medium"},
    {"resource": "user", "action": "invite", "sensitivity": "high"},
    {"resource": "user", "action": "disable", "sensitivity": "high"},
    {"resource": "user", "action": "unlock", "sensitivity": "medium"},
    {"resource": "user", "action": "reset_mfa", "sensitivity": "high"},
    {"resource": "service_account", "action": "create", "sensitivity": "high"},
    # 14) Roles / permissions
    {"resource": "role", "action": "read", "sensitivity": "medium"},
    {"resource": "role", "action": "create", "sensitivity": "high"},
    {"resource": "role", "action": "update", "sensitivity": "high"},
    {"resource": "role", "action": "assign", "sensitivity": "high"},
    {"resource": "permission", "action": "read", "sensitivity": "medium"},
    {"resource": "permission", "action": "update", "sensitivity": "critical"},
    # 15) Settings / org
    {"resource": "org_settings", "action": "read", "sensitivity": "low"},
    {"resource": "org_settings", "action": "update", "sensitivity": "high"},
    {"resource": "clinic_settings", "action": "read", "sensitivity": "low"},
    {"resource": "clinic_settings", "action": "update", "sensitivity": "medium"},
    {"resource": "template", "action": "manage", "sensitivity": "medium"},
    # 16) Reports / analytics
    {"resource": "reporting", "action": "read", "sensitivity": "medium",
     "sub": "operational"},
    {"resource": "reporting", "action": "read_financial", "sensitivity": "medium",
     "financial": True},
    {"resource": "reporting", "action": "read_clinical", "sensitivity": "high",
     "phi": True, "clinical": True},
    {"resource": "reporting", "action": "export", "sensitivity": "high", "export": True},
    {"resource": "reporting", "action": "export_phi", "sensitivity": "critical",
     "export": True, "phi": True},
    {"resource": "dashboard", "action": "read", "sensitivity": "low"},
    # 17) Integrations
    {"resource": "integration", "action": "read", "sensitivity": "medium"},
    {"resource": "integration", "action": "create", "sensitivity": "high"},
    {"resource": "integration", "action": "update", "sensitivity": "high"},
    {"resource": "integration", "action": "disable", "sensitivity": "high"},
    {"resource": "api_key", "action": "create", "sensitivity": "high"},
    {"resource": "api_key", "action": "rotate", "sensitivity": "high"},
    {"resource": "webhook", "action": "read", "sensitivity": "medium"},
    {"resource": "webhook", "action": "deliver", "sensitivity": "medium"},
    # 18) Privacy requests
    {"resource": "privacy_request", "action": "read", "sensitivity": "high"},
    {"resource": "privacy_request", "action": "create", "sensitivity": "medium"},
    {"resource": "privacy_request", "action": "verify_identity", "sensitivity": "high"},
    {"resource": "privacy_request", "action": "fulfill_export", "sensitivity": "critical",
     "export": True, "phi": True},
    {"resource": "privacy_request", "action": "fulfill_delete_anonymize",
     "sensitivity": "critical", "destructive": True},
    {"resource": "retention_policy", "action": "manage", "sensitivity": "high"},
    # 19) Auth / session / security controls
    {"resource": "self", "action": "change", "sensitivity": "low",
     "label": "self.password.change"},
    {"resource": "self", "action": "manage", "sensitivity": "low",
     "label": "self.mfa.manage"},
    {"resource": "session", "action": "read_self", "sensitivity": "low"},
    {"resource": "session", "action": "revoke_self", "sensitivity": "low"},
    {"resource": "session", "action": "revoke_other", "sensitivity": "high"},
    {"resource": "break_glass", "action": "activate", "sensitivity": "critical"},
    # 20) Destructive
    {"resource": "patient", "action": "archive", "sensitivity": "high", "destructive": True},
    {"resource": "patient", "action": "hard_delete", "sensitivity": "critical",
     "destructive": True},
]


def permission_key(resource: str, action: str) -> str:
    return f"{resource}.{action}"


# ---------------------------------------------------------------------------
# Role grants — derived from the Permission Matrix PDF.
#
# Each grant: (resource, action, scope, flags)
# flags is a set/str — any of: "MFA", "APR", "BG".
#
# We encode the matrix compactly; N cells are simply absent.
# ---------------------------------------------------------------------------

# short helpers
def g(res, act, scope="all_org", flags=""):
    return {"resource": res, "action": act, "scope": scope, "flags": flags}


ROLE_GRANTS: dict[str, list[dict]] = {
    # --------------- Super Admin (SA) ---------------
    # NOTE: the PDF matrix shows SA with APR on role.assign/create/update and
    # on integration/api_key/service_account/user.disable/user.reset_mfa. To
    # break the chicken-and-egg (need elevation to approve elevation) the SA
    # role — and only the SA role — is granted these with MFA-only. Every
    # other approver role (OO/CO) keeps the full MFA+APR posture. This is
    # documented in AUTHORIZATION_GUIDE.md §7.
    "super_admin": [
        g("patient", "read", "phi_limited"),
        g("patient_chart", "read", "phi_full", "MFA|BG"),
        g("soap_note", "read", "phi_full", "MFA|BG"),
        g("treatment_plan", "read", "phi_full", "MFA|BG"),
        g("appointment", "read", "phi_limited"),
        g("intake_form", "read", "phi_limited"),
        g("insurance", "read", "phi_limited"),
        g("billing", "read", "phi_limited"),
        g("claim", "read", "phi_limited"),
        g("remit", "read", "phi_limited"),
        g("document", "read", "phi_limited"),
        g("message", "read", "phi_limited"),
        g("consent", "read"),
        g("audit_log", "read", "all_org", "MFA"),
        g("security_event", "read", "all_org", "MFA"),
        g("user", "read"),
        g("user", "invite", "all_org", "MFA"),
        g("user", "disable", "all_org", "MFA"),
        g("user", "unlock", "all_org", "MFA"),
        g("user", "reset_mfa", "all_org", "MFA"),
        g("service_account", "create", "all_org", "MFA"),
        g("role", "read"),
        g("role", "create", "all_org", "MFA"),
        g("role", "update", "all_org", "MFA"),
        g("role", "assign", "all_org", "MFA"),
        g("permission", "read"),
        g("permission", "update", "all_org", "MFA"),
        g("org_settings", "read"),
        g("org_settings", "update", "all_org", "MFA"),
        g("clinic_settings", "read"),
        g("clinic_settings", "update", "all_org", "MFA"),
        g("template", "manage"),
        g("reporting", "read"),
        g("reporting", "read_financial", "phi_limited"),
        g("reporting", "read_clinical", "phi_limited"),
        g("reporting", "export", "all_org", "MFA"),
        g("dashboard", "read"),
        g("integration", "read"),
        g("integration", "create", "all_org", "MFA"),
        g("integration", "update", "all_org", "MFA"),
        g("integration", "disable", "all_org", "MFA"),
        g("api_key", "create", "all_org", "MFA"),
        g("api_key", "rotate", "all_org", "MFA"),
        g("webhook", "read"),
        g("retention_policy", "manage", "all_org", "MFA"),
        g("session", "revoke_other", "all_org", "MFA"),
        g("break_glass", "activate", "all_org", "MFA"),
        g("self", "change", "self"), g("self", "manage", "self"),
        g("session", "read_self", "self"), g("session", "revoke_self", "self"),
    ],
    # --------------- Org Owner (OO) ---------------
    "org_owner": [
        g("patient", "read", "phi_limited"),
        g("appointment", "read", "phi_limited"),
        g("intake_form", "read", "phi_limited"),
        g("insurance", "read", "phi_limited"),
        g("billing", "read"),
        g("billing", "export", "all_org", "MFA"),
        g("claim", "read", "phi_limited"),
        g("remit", "read", "phi_limited"),
        g("document", "read", "phi_limited"),
        g("document", "export", "all_org", "MFA|APR"),
        g("secure_message", "export", "all_org", "MFA|APR"),
        g("message", "read", "phi_limited"),
        g("consent", "read"),
        g("audit_log", "read", "all_org", "MFA"),
        g("security_event", "read", "all_org", "MFA"),
        g("access_review", "manage", "phi_limited", "MFA"),
        g("user", "read"), g("user", "invite", "all_org", "MFA"),
        g("user", "disable", "all_org", "MFA|APR"),
        g("user", "unlock", "all_org", "MFA"),
        g("user", "reset_mfa", "all_org", "MFA|APR"),
        g("service_account", "create", "phi_limited", "MFA|APR"),
        g("role", "read"),
        g("role", "create", "phi_limited", "MFA|APR"),
        g("role", "update", "phi_limited", "MFA|APR"),
        g("role", "assign", "all_org", "MFA|APR"),
        g("permission", "read"),
        g("org_settings", "read"),
        g("org_settings", "update", "all_org", "MFA|APR"),
        g("clinic_settings", "read"),
        g("clinic_settings", "update", "phi_limited", "MFA"),
        g("template", "manage", "phi_limited"),
        g("reporting", "read"), g("reporting", "read_financial"),
        g("reporting", "read_clinical", "phi_limited"),
        g("reporting", "export", "all_org", "MFA"),
        g("dashboard", "read"),
        g("integration", "read"),
        g("integration", "create", "phi_limited", "MFA|APR"),
        g("integration", "update", "phi_limited", "MFA|APR"),
        g("integration", "disable", "all_org", "MFA|APR"),
        g("api_key", "create", "phi_limited", "MFA|APR"),
        g("api_key", "rotate", "phi_limited", "MFA|APR"),
        g("webhook", "read"),
        g("privacy_request", "read", "phi_limited"),
        g("retention_policy", "manage", "all_org", "MFA|APR"),
        g("session", "revoke_other", "phi_limited", "MFA|APR"),
        g("self", "change", "self"), g("self", "manage", "self"),
        g("session", "read_self", "self"), g("session", "revoke_self", "self"),
    ],
    # --------------- Compliance Officer (CO) ---------------
    "compliance_officer": [
        g("patient", "read", "phi_limited"),
        g("patient_chart", "read", "phi_limited", "MFA"),
        g("soap_note", "read", "phi_limited", "MFA"),
        g("treatment_plan", "read", "phi_limited", "MFA"),
        g("appointment", "read", "phi_limited"),
        g("intake_form", "read", "phi_limited"),
        g("insurance", "read", "phi_limited"),
        g("billing", "read", "phi_limited"),
        g("billing", "export", "phi_limited", "MFA"),
        g("claim", "read", "phi_limited"),
        g("remit", "read", "phi_limited"),
        g("document", "read", "phi_limited"),
        g("document", "export", "phi_limited", "MFA|APR"),
        g("document", "purge", "all_org", "MFA|APR"),
        g("message", "read", "phi_limited"),
        g("consent", "read"), g("consent", "revoke", "all_org", "APR"),
        g("audit_log", "read", "all_org", "MFA"),
        g("audit_log", "export", "all_org", "MFA|APR"),
        g("phi_access_report", "read", "all_org", "MFA"),
        g("access_review", "manage", "all_org", "MFA"),
        g("security_event", "read", "all_org", "MFA"),
        g("user", "read"),
        g("user", "invite", "phi_limited", "MFA"),
        g("user", "disable", "phi_limited", "MFA|APR"),
        g("user", "unlock", "phi_limited", "MFA"),
        g("user", "reset_mfa", "phi_limited", "MFA|APR"),
        g("service_account", "create", "phi_limited", "MFA|APR"),
        g("role", "read"),
        g("role", "create", "phi_limited", "MFA|APR"),
        g("role", "update", "phi_limited", "MFA|APR"),
        g("role", "assign", "phi_limited", "MFA|APR"),
        g("permission", "read"),
        g("permission", "update", "phi_limited", "MFA|APR"),
        g("org_settings", "read"),
        g("org_settings", "update", "phi_limited", "MFA|APR"),
        g("clinic_settings", "read"),
        g("clinic_settings", "update", "phi_limited", "MFA"),
        g("reporting", "read"), g("reporting", "read_financial"),
        g("reporting", "read_clinical"),
        g("reporting", "export", "all_org", "MFA"),
        g("reporting", "export_phi", "all_org", "MFA|APR"),
        g("dashboard", "read"),
        g("integration", "read"),
        g("integration", "create", "phi_limited", "MFA|APR"),
        g("integration", "update", "phi_limited", "MFA|APR"),
        g("integration", "disable", "phi_limited", "MFA|APR"),
        g("api_key", "create", "phi_limited", "MFA|APR"),
        g("api_key", "rotate", "phi_limited", "MFA|APR"),
        g("webhook", "read", "phi_limited"),
        g("privacy_request", "read", "all_org"),
        g("privacy_request", "verify_identity", "all_org", "MFA|APR"),
        g("privacy_request", "fulfill_export", "all_org", "MFA|APR"),
        g("privacy_request", "fulfill_delete_anonymize", "all_org", "MFA|APR"),
        g("retention_policy", "manage", "all_org", "MFA|APR"),
        g("session", "revoke_other", "all_org", "MFA|APR"),
        g("break_glass", "activate", "all_org", "MFA|APR"),
        g("patient", "archive", "phi_limited", "MFA|APR"),
        g("self", "change", "self"), g("self", "manage", "self"),
        g("session", "read_self", "self"), g("session", "revoke_self", "self"),
    ],
    # --------------- Clinic Manager (CM) ---------------
    "clinic_manager": [
        g("patient", "read", "all_location_patients"),
        g("patient", "create", "assigned_location"),
        g("patient", "update", "assigned_location"),
        g("patient", "merge_duplicate", "assigned_location", "APR"),
        g("patient", "export", "assigned_location", "MFA|APR"),
        g("patient_chart", "read", "all_location_patients"),
        g("treatment_plan", "read", "all_location_patients"),
        g("appointment", "read", "all_location_patients"),
        g("appointment", "create", "assigned_location"),
        g("appointment", "update", "assigned_location"),
        g("appointment", "delete", "assigned_location"),
        g("waitlist", "manage", "assigned_location"),
        g("intake_form", "read", "all_location_patients"),
        g("intake_form", "create", "assigned_location"),
        g("intake_form", "update", "assigned_location"),
        g("intake_form", "lock", "assigned_location"),
        g("insurance", "read", "all_location_patients"),
        g("insurance", "create", "assigned_location"),
        g("insurance", "update", "assigned_location"),
        g("insurance", "export", "assigned_location", "MFA"),
        g("eligibility", "check", "assigned_location"),
        g("billing", "read", "all_location_patients"),
        g("billing", "export", "assigned_location", "MFA"),
        g("charge", "create", "assigned_location"),
        g("payment", "collect", "assigned_location"),
        g("payment", "refund", "assigned_location", "MFA|APR"),
        g("adjustment", "writeoff", "assigned_location", "MFA|APR"),
        g("billing", "void", "assigned_location", "MFA|APR"),
        g("claim", "read", "assigned_location"),
        g("remit", "read", "assigned_location"),
        g("document", "read", "all_location_patients"),
        g("document", "create", "assigned_location"),
        g("document", "update_metadata", "assigned_location"),
        g("document", "delete", "assigned_location", "MFA|APR"),
        g("document", "export", "assigned_location", "MFA|APR"),
        g("message", "read", "all_location_patients"),
        g("message", "create", "assigned_location"),
        g("broadcast", "create", "assigned_location", "MFA|APR"),
        g("consent", "read"), g("consent", "capture", "assigned_location"),
        g("consent", "revoke", "assigned_location"),
        g("audit_log", "read", "assigned_location", "MFA"),
        g("user", "read", "assigned_location"),
        g("user", "invite", "assigned_location", "MFA"),
        g("user", "disable", "assigned_location", "MFA|APR"),
        g("user", "unlock", "assigned_location", "MFA"),
        g("role", "read", "assigned_location"),
        g("role", "assign", "assigned_location", "MFA|APR"),
        g("permission", "read", "assigned_location"),
        g("org_settings", "read", "assigned_location"),
        g("clinic_settings", "read"),
        g("clinic_settings", "update", "assigned_location"),
        g("template", "manage", "assigned_location"),
        g("reporting", "read"), g("reporting", "read_financial"),
        g("reporting", "read_clinical", "assigned_location"),
        g("reporting", "export", "assigned_location", "MFA"),
        g("dashboard", "read"),
        g("integration", "read", "assigned_location"),
        g("privacy_request", "read", "assigned_location"),
        g("privacy_request", "create", "assigned_location"),
        g("privacy_request", "verify_identity", "assigned_location", "MFA"),
        g("patient", "archive", "assigned_location", "MFA|APR"),
        g("self", "change", "self"), g("self", "manage", "self"),
        g("session", "read_self", "self"), g("session", "revoke_self", "self"),
    ],
    # --------------- Front Desk (FD) ---------------
    "front_desk": [
        g("patient", "read", "all_location_patients"),
        g("patient", "create", "assigned_location"),
        g("patient", "update", "assigned_location"),
        g("appointment", "read", "all_location_patients"),
        g("appointment", "create", "assigned_location"),
        g("appointment", "update", "assigned_location"),
        g("appointment", "delete", "assigned_location"),
        g("waitlist", "manage", "assigned_location"),
        g("intake_form", "read", "all_location_patients"),
        g("intake_form", "create", "assigned_location"),
        g("intake_form", "update", "assigned_location"),
        g("insurance", "read", "all_location_patients"),
        g("insurance", "create", "assigned_location"),
        g("insurance", "update", "assigned_location"),
        g("eligibility", "check", "assigned_location"),
        g("billing", "read", "phi_limited"),
        g("payment", "collect", "assigned_location"),
        g("document", "read", "phi_limited"),
        g("document", "create", "assigned_location"),
        g("document", "update_metadata", "assigned_location"),
        g("document", "sign", "assigned_location"),
        g("document", "export", "assigned_location", "MFA|APR"),
        g("message", "read", "all_location_patients"),
        g("message", "create", "assigned_location"),
        g("consent", "read"), g("consent", "capture", "assigned_location"),
        g("consent", "revoke", "assigned_location"),
        g("clinic_settings", "read"),
        g("reporting", "read", "assigned_location"),
        g("dashboard", "read", "assigned_location"),
        g("privacy_request", "create", "assigned_location"),
        g("privacy_request", "verify_identity", "assigned_location", "MFA"),
        g("self", "change", "self"), g("self", "manage", "self"),
        g("session", "read_self", "self"), g("session", "revoke_self", "self"),
    ],
    # --------------- Provider (PR) ---------------
    "provider": [
        g("patient", "read", "assigned_patients"),
        g("patient", "create", "assigned_location"),
        g("patient", "update", "assigned_patients"),
        g("patient", "export", "assigned_patients", "MFA|APR"),
        g("patient_chart", "read", "assigned_patients"),
        g("patient_chart", "create", "assigned_patients"),
        g("patient_chart", "update", "assigned_patients"),
        g("patient_chart", "manage", "assigned_patients"),
        g("soap_note", "read", "assigned_patients"),
        g("soap_note", "create", "assigned_patients"),
        g("soap_note", "update", "assigned_patients"),
        g("soap_note", "sign", "assigned_patients"),
        g("treatment_plan", "read", "assigned_patients"),
        g("treatment_plan", "create", "assigned_patients"),
        g("treatment_plan", "update", "assigned_patients"),
        g("treatment_plan", "approve", "assigned_patients"),
        g("appointment", "read", "assigned_patients"),
        g("appointment", "create", "assigned_patients"),
        g("appointment", "update", "assigned_patients"),
        g("appointment", "delete", "assigned_patients"),
        g("intake_form", "read", "assigned_patients"),
        g("intake_form", "create", "assigned_patients"),
        g("intake_form", "update", "assigned_patients"),
        g("intake_form", "lock", "assigned_patients"),
        g("insurance", "read", "assigned_patients"),
        g("billing", "read", "assigned_patients"),
        g("charge", "create", "assigned_patients"),
        g("claim", "read", "assigned_patients"),
        g("coding", "update", "assigned_patients"),
        g("document", "read", "assigned_patients"),
        g("document", "create", "assigned_patients"),
        g("document", "update_metadata", "assigned_patients"),
        g("message", "read", "assigned_patients"),
        g("message", "create", "assigned_patients"),
        g("consent", "read"), g("consent", "capture", "assigned_patients"),
        g("consent", "revoke", "assigned_patients"),
        g("clinic_settings", "read"),
        g("template", "manage", "assigned_patients"),
        g("reporting", "read", "assigned_patients"),
        g("reporting", "read_clinical", "assigned_patients"),
        g("reporting", "export_phi", "assigned_patients", "MFA|APR"),
        g("dashboard", "read"),
        g("break_glass", "activate", "all_location_patients", "MFA|APR"),
        g("self", "change", "self"), g("self", "manage", "self"),
        g("session", "read_self", "self"), g("session", "revoke_self", "self"),
    ],
    # --------------- Clinical Staff (CS) ---------------
    "clinical_staff": [
        g("patient", "read", "assigned_patients"),
        g("patient", "create", "assigned_location"),
        g("patient", "update", "assigned_patients"),
        g("patient_chart", "read", "assigned_patients"),
        g("patient_chart", "create", "assigned_patients"),
        g("patient_chart", "update", "assigned_patients"),
        g("soap_note", "read", "assigned_patients"),
        g("soap_note", "create", "assigned_patients"),
        g("soap_note", "update", "assigned_patients"),
        g("treatment_plan", "read", "assigned_patients"),
        g("treatment_plan", "create", "assigned_patients"),
        g("treatment_plan", "update", "assigned_patients"),
        g("appointment", "read", "assigned_patients"),
        g("appointment", "create", "assigned_patients"),
        g("appointment", "update", "assigned_patients"),
        g("appointment", "delete", "assigned_patients"),
        g("intake_form", "read", "assigned_patients"),
        g("intake_form", "create", "assigned_patients"),
        g("intake_form", "update", "assigned_patients"),
        g("intake_form", "lock", "assigned_patients"),
        g("insurance", "read", "assigned_patients"),
        g("insurance", "create", "assigned_patients"),
        g("insurance", "update", "assigned_patients"),
        g("eligibility", "check", "assigned_patients"),
        g("document", "read", "assigned_patients"),
        g("document", "create", "assigned_patients"),
        g("document", "update_metadata", "assigned_patients"),
        g("document", "export", "assigned_patients", "MFA|APR"),
        g("message", "read", "assigned_patients"),
        g("message", "create", "assigned_patients"),
        g("consent", "read"), g("consent", "capture", "assigned_patients"),
        g("consent", "revoke", "assigned_patients"),
        g("clinic_settings", "read"),
        g("reporting", "read", "assigned_patients"),
        g("reporting", "read_financial"),
        g("reporting", "export", "assigned_patients", "MFA"),
        g("dashboard", "read"),
        g("self", "change", "self"), g("self", "manage", "self"),
        g("session", "read_self", "self"), g("session", "revoke_self", "self"),
    ],
    # --------------- Billing Specialist (BS) ---------------
    "billing_specialist": [
        g("patient", "read", "phi_limited"),
        g("patient", "export", "phi_limited", "MFA|APR"),
        g("appointment", "read", "phi_limited"),
        g("intake_form", "read", "phi_limited"),
        g("insurance", "read", "phi_limited"),
        g("insurance", "create"), g("insurance", "update"),
        g("insurance", "export", "phi_limited", "MFA"),
        g("eligibility", "check"),
        g("billing", "read"), g("billing", "export", "all_org", "MFA"),
        g("charge", "create"),
        g("payment", "collect"),
        g("payment", "refund", "all_org", "MFA|APR"),
        g("adjustment", "writeoff", "all_org", "MFA|APR"),
        g("billing", "void", "all_org", "MFA|APR"),
        g("claim", "read"), g("claim", "create"),
        g("claim", "submit"), g("claim", "correct_resubmit"),
        g("remit", "read"),
        g("coding", "update"),
        g("document", "read", "phi_limited"),
        g("document", "export", "phi_limited", "MFA|APR"),
        g("message", "read", "phi_limited"),
        g("message", "create"),
        g("secure_message", "export", "phi_limited", "MFA|APR"),
        g("audit_log", "read", "all_org", "MFA"),
        g("audit_log", "export", "all_org", "MFA|APR"),
        g("phi_access_report", "read", "all_org", "MFA"),
        g("access_review", "manage", "phi_limited", "MFA"),
        g("security_event", "read", "all_org", "MFA"),
        g("org_settings", "read", "phi_limited"),
        g("clinic_settings", "read"),
        g("reporting", "read"), g("reporting", "read_financial"),
        g("reporting", "export", "all_org", "MFA"),
        g("reporting", "export_phi", "all_org", "MFA|APR"),
        g("dashboard", "read"),
        g("privacy_request", "fulfill_export", "all_org", "MFA|APR"),
        g("billing", "void", "all_org", "MFA|APR"),
        g("self", "change", "self"), g("self", "manage", "self"),
        g("session", "read_self", "self"), g("session", "revoke_self", "self"),
    ],
    # --------------- Auditor (AU) ---------------
    "auditor": [
        g("patient", "read", "phi_limited"),
        g("patient_chart", "read", "phi_limited", "MFA"),
        g("appointment", "read", "phi_limited"),
        g("intake_form", "read", "phi_limited"),
        g("insurance", "read", "phi_limited"),
        g("billing", "read", "phi_limited"),
        g("billing", "export", "phi_limited", "MFA"),
        g("claim", "read", "phi_limited"),
        g("remit", "read", "phi_limited"),
        g("document", "read", "phi_limited"),
        g("message", "read", "phi_limited"),
        g("consent", "read"),
        g("reporting", "read_financial", "phi_limited"),
        g("reporting", "read_clinical", "phi_limited"),
        g("dashboard", "read", "phi_limited"),
        g("role", "read"), g("permission", "read"),
        g("privacy_request", "read", "all_org"),
        g("integration", "read", "phi_limited"),
        g("self", "change", "self"), g("self", "manage", "self"),
        g("session", "read_self", "self"), g("session", "revoke_self", "self"),
    ],
    # --------------- Patient Portal (PP) ---------------
    "patient_portal": [
        g("patient", "read", "self"),
        g("patient", "create", "self"),           # self registration only
        g("patient", "update", "self"),
        g("patient", "export", "self"),
        g("patient_chart", "read", "self"),
        g("soap_note", "read", "self"),           # only if shared
        g("treatment_plan", "read", "self"),      # only if shared
        g("appointment", "read", "self"),
        g("appointment", "create", "self"),
        g("appointment", "update", "self"),
        g("appointment", "delete", "self"),
        g("intake_form", "read", "self"),
        g("intake_form", "create", "self"),
        g("intake_form", "update", "self"),
        g("insurance", "read", "self"),
        g("insurance", "create", "self"),
        g("insurance", "update", "self"),
        g("insurance", "export", "self"),
        g("eligibility", "check", "self"),
        g("billing", "read", "self"),
        g("billing", "export", "self"),
        g("payment", "collect", "self"),
        g("document", "read", "self"),
        g("document", "create", "self"),
        g("document", "sign", "self"),
        g("document", "export", "self"),
        g("message", "read", "self"),
        g("message", "create", "self"),
        g("secure_message", "export", "self"),
        g("consent", "read", "self"),
        g("consent", "capture", "self"),
        g("consent", "revoke", "self"),
        g("privacy_request", "read", "self"),
        g("privacy_request", "create", "self"),
        g("reporting", "read", "self"),
        g("reporting", "read_financial", "self"),
        g("reporting", "read_clinical", "self"),
        g("reporting", "export_phi", "self"),
        g("dashboard", "read", "self"),
        g("api_key", "rotate", "self"),
        g("user", "read", "self"),
        g("self", "change", "self"), g("self", "manage", "self"),
        g("session", "read_self", "self"), g("session", "revoke_self", "self"),
    ],
    # --------------- Integration Service Account (IA) ---------------
    "integration_account": [
        g("patient", "read", "no_phi"),
        g("appointment", "read", "no_phi"),
        g("appointment", "create", "no_phi"),
        g("appointment", "update", "no_phi"),
        g("appointment", "delete", "no_phi"),
        g("intake_form", "read", "no_phi"),
        g("intake_form", "create", "no_phi"),
        g("intake_form", "update", "no_phi"),
        g("insurance", "read", "no_phi"),
        g("insurance", "create", "no_phi"),
        g("insurance", "update", "no_phi"),
        g("eligibility", "check", "no_phi"),
        g("billing", "read", "no_phi"),
        g("charge", "create", "no_phi"),
        g("payment", "collect", "no_phi"),
        g("claim", "read", "no_phi"),
        g("claim", "create", "no_phi"),
        g("claim", "submit", "no_phi"),
        g("claim", "correct_resubmit", "no_phi"),
        g("remit", "read", "no_phi"),
        g("document", "read", "no_phi"),
        g("document", "create", "no_phi"),
        g("document", "update_metadata", "no_phi"),
        g("message", "read", "no_phi"),
        g("message", "create", "no_phi"),
        g("consent", "read", "no_phi"),
        g("clinic_settings", "read", "no_phi"),
        g("dashboard", "read", "no_phi"),
        g("reporting", "read", "no_phi"),
        g("reporting", "read_financial", "no_phi"),
        g("integration", "read", "no_phi"),
        g("webhook", "read", "no_phi"),
        g("webhook", "deliver"),
    ],
}

# ---------------------------------------------------------------------------
# Privileged permission keys — for the "privileged user" report and to
# short-circuit UI rendering.
# ---------------------------------------------------------------------------

PRIVILEGED_PERMISSIONS: set[str] = {
    "role.create", "role.update", "role.assign",
    "permission.update",
    "user.disable", "user.reset_mfa", "service_account.create",
    "audit_log.read", "audit_log.export",
    "reporting.export_phi",
    "api_key.create", "api_key.rotate",
    "integration.create", "integration.update", "integration.disable",
    "payment.refund", "adjustment.writeoff", "billing.void",
    "privacy_request.fulfill_export", "privacy_request.fulfill_delete_anonymize",
    "retention_policy.manage",
    "break_glass.activate",
    "patient.archive", "patient.hard_delete",
    "session.revoke_other",
    "document.purge", "document.delete",
}
